### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by kuznetsovin** [weskinner/symbol-gen#11]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Users/igorkuznetsov/Downloads/Atom.app/Contents/Resources/app/src/atom.js:55:11)
SymbolGenView.initialize (/Users/igorkuznetsov/.atom/packages/symbol-gen/lib/symbol-gen-view.coffee:16:9)
```

**Comment by weskinner** [comment]
Fixed in 3045c5
