### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [weskinner/symbol-gen#26]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.3.0`) of this package:

1. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: ```json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] } ```
1. The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
1. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see what deprecations are being reported on this package.

See https://github.com/atom/atom/issues/6867 for more info.

**Comment by weskinner** [comment]
resolved in f362ec4d1658d82b2d059e0d4bc5dafb08e3341a

**Comment by djpowers** [comment]
Thanks for the update! :+1:
