### ISSUE TITLE
Symbols auto generating now?

### ISSUE THREAD

**Issue by WouterDS** [weskinner/symbol-gen#31]
Are symbols autogenerating now? Every once in a while I notice my Macbook is getting super slow and when I check the process list "ctags-darwin" is always claiming all of my resources.. There does not seem to be any setting inside of the package to enable or disable this?

**Comment by baelter** [comment]
Correct, once you generated tags once for a project it symbols-gen will keep those tagfiles up to date with your source.

**Comment by WouterDS** [comment]
Well, it's killing my laptop (Macbook Pro Retina '14). Eventually, me and my colleagues removed the plugin because it was making our laptops almost freeze every x minutes.

**Comment by baelter** [comment]
You could create a .ctags (in project or globally in ~/) file with excludes for e.g. bower_components, build/target etc. to avoid creating unnecessary tags for dependencies/concat/minified files etc.
http://ctags.sourceforge.net/ctags.html#OPTIONS

**Comment by WouterDS** [comment]
I'll give that a try and will come back to this after some testing, thanks @baelter.
