### ISSUE TITLE
Better name for metadata file

### ISSUE THREAD

**Issue by mcandre** [weskinner/symbol-gen#35]
symbol-gen stores symbols in a file with a very generic name, `tags`, that is difficult to ignore in version control (many projects will have a file or folder called `tags` that they *do* want to include).

Please consider renaming the symbols file to something more VCS friendly, such as `.tags`.

**Comment by douggr** [comment]
There you go: add `-f .friedly-name` to your .ctags file.

**-f tagfile**
> Use the name specified by tagfile for the tag file (default is "tags", or "TAGS" when running in etags mode). If tagfile is specified as "−", then the tag file is written to standard output instead.

**Comment by douggr** [comment]
Nah, nevermind. It's hardcoded in [@L61](https://github.com/weskinner/symbol-gen/blob/master/lib/symbol-gen-view.coffee#L61). My bad.

**Comment by weskinner** [comment]
now using ".tags"
