### ISSUE TITLE
Windows / Linux Keybinding

### ISSUE THREAD

**Issue by onetrev** [weskinner/symbol-gen#38]
Just wondering if you could add a Generate Symbols keybinding for Windows / Linus folks, please?

Definitely us non-mac folk can add it to their keybindings but thought it should be included out of the box if possible. Thanks a ton!

**Comment by llawlor** [comment]
:+1:

**Comment by Jan-Osch** [comment]
Yes please :+1:

**Comment by trainto** [comment]
The key bindings for go-to-declaration and return-from-declaration are defined in the Symbols View package which is ATOM core package, not this symbol-gen package.
It should be done by Symbols View package.

In my case ctrl-alt-shift-down and ctrl-alt-shit-up are set to each go-to-declaration and return-from-declaration, also if you guys use vim mode package, those can be done by ctrl-] and ctrl-t.

**Comment by onetrev** [comment]
Sorry, but I have no idea what you are talking about. This is the keybinding from this package we want, and it's clearly only setup for Mac right now.

+'atom-workspace':
   'cmd-alt-g': 'symbol-gen:generate'

**Comment by trainto** [comment]
Sorry, my mistake.
I thougt you were mentioning  about go to declaration key binding.

**Comment by trainto** [comment]
I've made a PR('ctrl-alt-g': 'symbol-gen:generate' for Windows and Linux) for this request, but I'm not sure it'll be accepted.. owner of this project seems that he stopped managing this repository.

**Comment by onetrev** [comment]
Awesome, thanks for doing that @trainto. Not sure why I didn't do that as it's such and easy edit. Fingers crossed package author comes back to accept your PR. Thanks again!!
