### ISSUE TITLE
Ignore .gitignore'd files & other ignore patterns

### ISSUE THREAD

**Issue by forivall** [weskinner/symbol-gen#42]
When I generate tags for a babel (es6 -> es5 transpile), the generated files are also indexed. However, those files are ignored by source control, and should be ignored by symbol-gen. Ideally, all files ignored by any VCS should be ignored when generating symbols. It would also be useful to allow custom global ignore patterns, and also add ignore patterns from a `.atom-symbol-gen-ignore` file.

**Comment by pajtai** [comment]
Not sure I agree with automatically not generating symbols for gitignored things. If you have a library in your node_modules it is very useful to be able to jump to the definition of the methods created by the library.... custom ignore patterns would be very useful.

**Comment by derwaldgeist** [comment]
It would be nice if the package would allow me to ignore all files and folders that I defined as "Ignored Names" in Atom's settings.

Plus, it would be great if there was a syntax documentation for the .ctags file. For instance, I would like to know what delimiter the --exclude option is using to separate names (or if it has to be placed more than once if you want to exclude more names).

**Comment by weskinner** [comment]
resolved in v1.3.0

**Comment by awilkins** [comment]
This doesn't seem to work ; it's generating tags for several folders I have ignored. I get a 200MB tag file whereas a hand-crafted invocation of the `ctags` program using `find` for the set I want is only 63kB.

**Comment by adamserafini** [comment]
@awilkins I am finding the same issue, I created a new ticket: #60
