### ISSUE TITLE
tags file location

### ISSUE THREAD

**Issue by samvaran** [weskinner/symbol-gen#47]
Is it possible to specify where to store the tags file for a project, or store it outside the project by default? I don't want to have to worry about it every time I'm running  "git add"  or accidentally commit and push a 20MB text file to my project that's being shared with many other people.

**Comment by tusharmath** [comment]
add the following line to your `.gitignore` file —

```
tags
```

**Comment by samvaran** [comment]
Yes, but the issue is that in many organizations, the .gitignore file is shared between everyone pulling from that branch and it may not always be appropriate to add a line called "tags" to everyone's .gitignore file just for your own personal benefit. 

I got around this issue, however, but adding it to my global gitignore file:
https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by maackle** [comment]
+1, it's pretty presumptuous to have to .gitignore a file with such a prominent name. There should be configuration for the filename, or at least name it `.tags` by default to sweep it under the rug a little more.

**Comment by weskinner** [comment]
v1.3.0 uses ".tags"
