### ISSUE TITLE
Auto generating ctags on-save blocks the editor

### ISSUE THREAD

**Issue by wonderbeyond** [weskinner/symbol-gen#57]
How about providing an option for not generating ctags on save? It's too slow and blocking my editor is interactivity.

Thanks!

**Comment by wonderbeyond** [comment]
I'm so sorry that I've given the wrong conclusion!

My editor is still blocking on save even if I've disabled `symbol-gen` package.

Then I found who is blocking my editor is [linter-jscs](https://atom.io/packages/linter-jscs) package.

**Comment by wonderbeyond** [comment]
I've reposted to `linter-jscs` project: https://github.com/AtomLinter/linter-jscs/issues/291

**Comment by IBaiBai** [comment]
朋友，你现在还有这个问题吗

**Comment by wonderbeyond** [comment]
保存时的阻塞是jscs导致的，不用就好了。symbol-gen关了当然不会自动生成tags文件了。

**Comment by IBaiBai** [comment]
@wonderbeyond 我这儿解决了，谢谢！我昨天修改了一下symbol-gen的源码，有三行(saee,save as,save all)，删了save保存的时候就不会更新.tags了，然后ctrl+alt+g生成

**Comment by wonderbeyond** [comment]
手动触发更新tags容易忘记啊，保存自动更新让你有什么困扰吗？
